language: node_js
branches:
  only:
    - master
node_js:
  - "node"
install:
  - npm install
script:
  - npm run build
deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key: $NPM_TOKEN
  skip-cleanup: true
  verbose: true
  on:
    branch: master
